services:
  api:
    image: node:20-alpine
    working_dir: /usr/src/app
    user: node
    environment:
      - NODE_ENV=production
    ports:
      - "9230:9230"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    command: sh -c "npm install --only=production && node --inspect=0.0.0.0:9230 index.js"
    networks:
      - tofu_net

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: broccoli
      MYSQL_USER: veganburger
      MYSQL_PASSWORD: tofu
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tofu_net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./private.key:/etc/nginx/ssl/private.key:ro
      - ./fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
    depends_on:
      - api
    networks:
      - tofu_net

networks:
  tofu_net:

